# Generated by Django 4.2.1 on 2023-05-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labitemtype', models.CharField(max_length=100)),
                ('labitemsubtype', models.CharField(max_length=100)),
                ('labitemid', models.IntegerField(max_length=10)),
                ('labitemname', models.CharField(max_length=100)),
            ],
        ),
    ]
