# Generated by Django 4.2.1 on 2023-05-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_chemicals_labitemid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chemicals',
            new_name='Chemical',
        ),
    ]
