# Generated by Django 4.2.1 on 2023-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_chemicals_chemical'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
