# Generated by Django 4.2.1 on 2023-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_chemical_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
