# Generated by Django 4.2.1 on 2023-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_chemical_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='documents',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
