# Generated by Django 4.2.1 on 2023-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_chemical_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='custom_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
