# Generated by Django 4.2.1 on 2023-05-19 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_chemical_custom_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='custom_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
