# Generated by Django 4.2.1 on 2023-05-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_customname_remove_chemical_custom_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomName',
        ),
    ]
