# Generated by Django 4.2.1 on 2023-05-19 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_delete_customname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='custom_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
