# Generated by Django 4.2.1 on 2023-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_chemical_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
