# Generated by Django 4.2.1 on 2023-05-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_chemical_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='additional_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
